version: '3.5'

services:
  
  consignment:
    restart: always
    build: ./shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
  
  vessel:
    restart: always
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  # commands
  # cli:
  #   build: ./shippy-cli-consignment
  
  # database
  datastore:
    image: mongodb
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensure data presistence between restarting
    ports:
      - 27017
    command: mongod --logpath=/dev/null